# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91cbbf0258e45cfdbb21905e9911fa2a5f5fa92ce32661fd38fb9feac5f9d4303ae4fbdc1ad8db7c0e733d4ad78bff9b718c19f74b1c06fee49bcf94987bb44e

test:
  secret_key_base: fa608eb72eee7e1453c2f3677da970664c7769a6a98179f098f797e1c37ee17e5b1da0f9e61d14e6faaeb435c97d1f2382b3f20e004fed177f49a363015c7490

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
